services:
  postgres:
    image: postgres:latest
    container_name: multitenant

    environment:
      POSTGRES_DB: multitenant_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Oluwafunke3060$"
      PGDATA: /var/lib/postgresql/data/data

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - multitenant-network

    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  multitenant-network:
    driver: bridge