services:
  postgres:
    image: postgres:latest
    container_name: multitenant
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/data
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/data
    networks:
      - multitenant-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  multitenant-network:
    driver: bridge
